# Data Transformation

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

In [9]:
mba = pd.read_csv("C:\\Users\\nikhi\\OneDrive\\Desktop\\Social Prachar\\Excel files\\mba.csv")
mba

Datasrno  workex  gmat
0           1      21   720
1           2     107   640
2           3      57   740
3           4      99   690
4           5     208   710
..        ...     ...   ...
768       769      88   620
769       770     132   670
770       771      28   610
771       772      10   610
772       773      52   620

[773 rows x 3 columns]

In [10]:
del mba['Datasrno']

In [11]:
mba

workex  gmat
0        21   720
1       107   640
2        57   740
3        99   690
4       208   710
..      ...   ...
768      88   620
769     132   670
770      28   610
771      10   610
772      52   620

[773 rows x 2 columns]

# Standardization (x-u/sigma)

In [14]:
from sklearn import preprocessing
# Scaler is a function used to create the standard function
scaler = preprocessing.StandardScaler() 

In [15]:
mba1 = scaler.fit(mba) # Applied on the dataset
mba1 = scaler.transform(mba) # It will convert the values into scaled data

In [16]:
mba1

array([[-1.3336917 ,  0.30134669],
       [ 1.80853813, -2.42709832],
       [-0.01833968,  0.98345794],
       ...,
       [-1.07792881, -3.4502652 ],
       [-1.73560482, -3.4502652 ],
       [-0.20102746, -3.10920957]])

In [17]:
# Second Method
# We can us the scale function to standardize the data
# Scale function is available under sklearn module

from sklearn.preprocessing import scale
mba2 = scale(mba)
mba2

array([[-1.3336917 ,  0.30134669],
       [ 1.80853813, -2.42709832],
       [-0.01833968,  0.98345794],
       ...,
       [-1.07792881, -3.4502652 ],
       [-1.73560482, -3.4502652 ],
       [-0.20102746, -3.10920957]])

# Normalization (x-minx/Range)- Rescale the Data

In [18]:
from sklearn.preprocessing import MinMaxScaler
# Scaler is a function used to create the standard function
# scaler = preprocessing.StandardScaler()

In [19]:
scale = MinMaxScaler()

In [20]:
mba3 = scale.fit(mba)
mba3 = scale.transform(mba)
mba3

array([[0.04444444, 0.66666667],
       [0.36296296, 0.22222222],
       [0.17777778, 0.77777778],
       ...,
       [0.07037037, 0.05555556],
       [0.0037037 , 0.05555556],
       [0.15925926, 0.11111111]])

In [23]:
# Second Method
mba4 = (mba-mba.min())/(mba.max()-mba.min())
mba4

workex      gmat
0    0.044444  0.666667
1    0.362963  0.222222
2    0.177778  0.777778
3    0.333333  0.500000
4    0.737037  0.611111
..        ...       ...
768  0.292593  0.111111
769  0.455556  0.388889
770  0.070370  0.055556
771  0.003704  0.055556
772  0.159259  0.111111

[773 rows x 2 columns]